# Generated by Django 4.0.4 on 2022-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
